import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Play,ArrowRight,ShieldCheck,Gamepad2,Box,Glasses,Plane,Cpu,ChevronRight,X,Image as ImageIcon,Film}from'lucide-react';import'./styles.css';
const I=n=>`/images/new-${String(n).padStart(2,'0')}.webp`;
const spaces=[
['Technology Center Entry',I(18),'The Center arrival experience introduces students and visitors to Hampton’s technology story and connects the major learning environments.','Entry · Welcome · Orientation'],
['VR + Immersive Technology',I(13),'The large immersive display environment supports VR/XR, simulation, interactive visualization and room-scale learning experiences.','VR/XR · Simulation · Immersive Learning'],
['Presentation + Learning Space',I(23),'The presentation room with the large black display supports instruction, demonstrations, lectures and collaborative presentations.','Presentation · Teaching · Collaboration'],
['Learning Pods + Collaboration',I(24),'Flexible tables and shared technology support coursework, team projects, research collaboration and presentations.','Learning Pods · Collaboration · Projects'],
['Robotics + Drone Cage',I(16),'The protected drone cage supports robotics and drone testing, demonstrations and hands-on technical projects above the Student Center atrium.','Robotics · Drones · Engineering'],
['Immersive Health + Anatomy',I(19),'Interactive anatomy and clinical visualization systems support health sciences, simulation and interdisciplinary research.','Healthcare · Simulation · Research'],
['Esports Gaming Lounge',I(21),'A dedicated esports environment supports organized student activities, competition, gaming and creative technology.','Esports · Gaming · Student Life'],
['Podcast + Digital Media',I(14),'A media-focused environment for interviews, recording, cameras, content development and student portfolios.','Podcast · Cameras · Media']];
const tech=[
['VR / XR Headsets',Glasses,'Immersive headsets and supporting accessories for virtual reality, spatial computing and simulation.','Students, faculty, researchers','Virtual labs, design review, simulation, immersive instruction'],
['AI Workstations',Cpu,'High-performance computing stations configured for AI development, visualization, data science and creative technology.','Students, researchers, project teams','Model development, visualization, coding, data research'],
['Robotics Platforms',Box,'Programmable mobile and robotic systems for autonomy, controls, sensing and applied engineering.','Engineering, CS, research teams','Prototyping, autonomy, controls and interdisciplinary projects'],
['Drone Systems',Plane,'Drone platforms supported by a protected cage environment for safe flight testing and instruction.','Robotics teams, faculty, researchers','Flight training, autonomy, sensing, mapping and research']];
function Btn({children,onClick,ghost=false}){return <button className={ghost?'btn ghost':'btn'} onClick={onClick}>{children}<ArrowRight size={16}/></button>}
function App(){const[entered,setEntered]=useState(false),[page,setPage]=useState('Home'),[modal,setModal]=useState(null);const go=p=>{setPage(p);scrollTo({top:0,behavior:'smooth'})};if(!entered)return <Landing enter={()=>{setEntered(true);setPage('Home')}}/>;const tabs=['Vision','Explore the Center','Technology','Esports','Safety','Videos','Contact'];return <div><header><button className="wordmark logoHome" aria-label="Home" onClick={()=>go('Home')}><img src="/images/hampton-wordmark-white.png" alt="Hampton University"/></button><nav>{tabs.map(t=><button key={t} className={page===t?'active':''} onClick={()=>go(t)}>{t}</button>)}</nav><Btn onClick={()=>go('Invest')}>INVEST NOW</Btn></header><main>{page==='Home'?<Home go={go}/>:page==='Explore the Center'?<Explore setModal={setModal}/>:page==='Technology'?<Technology/>:page==='Esports'?<Esports go={go}/>:page==='Safety'?<Safety/>:page==='Videos'?<Videos/>:page==='Vision'?<Vision/>:page==='Invest'?<Simple title="INVEST IN THE FUTURE" head="HELP BUILD WHAT'S NEXT." img={I(8)} text="A donor-focused destination for the vision, opportunities for support and Hampton University's approved giving pathway."/>:<Simple title="CONTACT" head="CONNECT WITH THE CENTER." img={I(2)} text="Contact information, design-team details and Hampton-approved project contacts can be added here as the campaign advances."/>}</main><footer><b>HAMPTON UNIVERSITY · TECHNOLOGY & AI CENTER</b><span>THE STANDARD OF EXCELLENCE</span></footer>{modal&&<Modal data={modal} close={()=>setModal(null)}/>}</div>}
function Landing({enter}){return <section className="landing"><div className="landingMedia"><img src="/images/portal-boat-ai-center.webp"/></div><div className="landingShade"></div><div className="portalHud"><span>HAMPTON UNIVERSITY</span><b>TECHNOLOGY & AI CENTER</b></div><div className="landingCopy"><span className="kicker">ARRIVING AT HAMPTON UNIVERSITY</span><h1>ENTER THE<br/><i>FUTURE.</i></h1><p>A cinematic waterfront arrival into Hampton's Technology & AI Center.</p><button className="enter" onClick={enter}><Play fill="currentColor"/> ENTER THE EXPERIENCE</button></div><div className="loadPanel"><b>SYSTEM ARRIVAL</b><span className="done">✓ CAMPUS IDENTIFIED</span><span>◉ LOADING SPACES</span><span>◉ LOADING VIDEOS</span><span>◉ PREPARING EXPERIENCE</span><button onClick={enter}>READY TO DONATE? <ArrowRight size={15}/></button></div></section>}
function Home({go}){return <><section className="hero"><div className="heroCopy"><span className="kicker">HAMPTON UNIVERSITY · TECHNOLOGY & AI CENTER</span><h1>THE FUTURE<br/>LIVES <i>HERE.</i></h1><p>A collaborative research and learning environment built around immersive technology, health simulation, robotics, AI, esports and the ideas that come next.</p><div className="row"><Btn onClick={()=>go('Explore the Center')}>EXPLORE THE CENTER</Btn><Btn ghost onClick={()=>go('Videos')}><Play size={15}/> WATCH THE VISION</Btn></div></div><div className="trueHolo"><img src={I(4)}/><span>ARCHITECTURAL HOLOGRAM // CENTER MODEL</span></div></section><section className="quick"><button onClick={()=>go('Explore the Center')}>06+ <span>Signature Spaces</span></button><button onClick={()=>go('Technology')}>TECH <span>Equipment + Systems</span></button><button onClick={()=>go('Esports')}>HU <span>Esports Experience</span></button><button onClick={()=>go('Safety')}>SAFE <span>Standards + Operations</span></button></section><section className="split"><img src={I(8)}/><div><span className="kicker">PEOPLE · PURPOSE · POSSIBILITIES</span><h2>A CENTER BUILT TO<br/>CONNECT DISCIPLINES.</h2><p>Explore spaces as individual stories, understand the technology going inside them, and see how each environment can support student learning, faculty research and industry collaboration.</p><Btn onClick={()=>go('Explore the Center')}>ENTER SPACES</Btn></div></section></>}
function Vision(){return <><section className="pageHero"><span className="kicker">DESIGN VISION</span><h1>A CENTER FOR PEOPLE,<br/>POSSIBILITY & PROGRESS.</h1><p>Tradition meets emerging technology in a center designed to make experimentation visible, collaborative and accessible.</p></section><section className="wideImage"><img src={I(6)}/></section><section className="split reverse"><img src={I(1)}/><div><h2>THE STANDARD OF EXCELLENCE, REIMAGINED.</h2><p>The Technology & AI Center is envisioned as a flexible research and learning facility inside the Hampton Student Center—supporting science, engineering, healthcare, creative technology, career development and industry partnership.</p></div></section></>}
function Explore({setModal}){return <><section className="pageHero"><span className="kicker">EXPLORE THE CENTER</span><h1>EVERY SPACE HAS<br/>A PURPOSE.</h1><p>Explore each environment like a mini feature story. Open a space for its render gallery, program intent, student uses and full experience video slot.</p></section><section className="spaceGrid">{spaces.map((s,i)=><article className="space" key={s[0]}><img src={s[1]}/><div><small>{s[3]}</small><h2>{s[0]}</h2><p>{s[2]}</p><div className="twobtn"><button onClick={()=>setModal(s)}><ImageIcon/> VIEW GALLERY</button><button onClick={()=>setModal(s)}><Film/> FULL VIDEO</button></div></div></article>)}</section></>}
function Technology(){return <><section className="pageHero"><span className="kicker">TECHNOLOGY CATALOG</span><h1>WHAT'S GOING<br/>INSIDE.</h1><p>Browse the Center's technology like a premium equipment catalog—what it is, who can use it, and what it unlocks. No pricing is shown.</p></section><section className="catalog">{tech.map(([n,Icon,d,who,use],i)=><article><div className="productVisual"><Icon size={64}/><span>TECH {String(i+1).padStart(2,'0')}</span></div><div className="productCopy"><small>HAMPTON TECHNOLOGY SYSTEM</small><h2>{n}</h2><p>{d}</p><dl><dt>WHO COULD USE IT</dt><dd>{who}</dd><dt>STUDENT + RESEARCH VALUE</dt><dd>{use}</dd><dt>INCLUDES</dt><dd>Core system · supporting accessories · instructional integration · shared-use setup</dd></dl><button>VIEW EQUIPMENT DETAILS <ChevronRight/></button></div></article>)}</section></>}
function Esports({go}){return <><section className="esHero"><img src={I(20)}/><div><span className="kicker">HAMPTON ESPORTS</span><h1>PLAY.<br/>COMPETE.<br/>CREATE.</h1><p>A dedicated digital competition and creative technology experience for students, teams and media production.</p><Btn onClick={()=>go('Videos')}>WATCH ESPORTS EXPERIENCE</Btn></div></section><section className="gallery3"><img src={I(19)}/><img src={I(21)}/><img src={I(22)}/></section></>}
function Safety(){return <><section className="pageHero"><span className="kicker">SAFETY + STANDARDS</span><h1>INNOVATION,<br/>RESPONSIBLY.</h1><p>Technology-rich environments need clear operational standards. This section communicates the Center's approach to protected testing, accessibility, supervision and responsible use.</p></section><section className="safetyLead"><img src={I(17)}/><div><ShieldCheck size={50}/><h2>ROBOTICS + DRONE CAGE</h2><p>The protected robotics enclosure is positioned over the Student Center atrium, creating a visible testing environment while separating flight operations from surrounding circulation.</p><ul><li>Controlled drone and robotics testing zone</li><li>Physical separation from public circulation</li><li>Supervised equipment operation</li><li>Clear pre-flight / shutdown procedures</li><li>Accessible viewing and learning opportunities</li></ul></div></section><section className="standards"><article><b>01</b><h3>Operational Safety</h3><p>Training, supervision, equipment check-out and room-specific operating procedures.</p></article><article><b>02</b><h3>Technology Standards</h3><p>Managed systems, secure networks, maintenance protocols and responsible AI/data practices.</p></article><article><b>03</b><h3>Accessible Design</h3><p>Inclusive routes, interfaces and learning environments designed to support broad student access.</p></article><article><b>04</b><h3>Research Readiness</h3><p>Spaces organized to support documented procedures, faculty oversight and repeatable testing.</p></article></section></>}
function Videos(){let vids=[[I(5),'Center Vision'],[I(15),'Health + Anatomy'],[I(19),'Immersive Athletics'],[I(17),'Robotics + Drones'],[I(20),'Esports'],[I(18),'Center Arrival']];return <><section className="pageHero"><span className="kicker">VIDEO EXPERIENCES</span><h1>SEE THE CENTER<br/>IN MOTION.</h1><p>Each card is ready to connect to a Cloudinary-hosted full video while keeping large video files out of the website repository.</p></section><section className="videoGrid">{vids.map(v=><article><img src={v[0]}/><div className="play"><Play fill="currentColor"/></div><h3>{v[1]}</h3><span>FULL EXPERIENCE VIDEO SLOT</span></article>)}</section></>}
function Simple({title,head,img,text}){return <><section className="pageHero"><span className="kicker">{title}</span><h1>{head}</h1><p>{text}</p></section><section className="wideImage"><img src={img}/></section></>}
function Modal({data,close}){return <div className="modal" onClick={close}><div onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><img src={data[1]}/><small>{data[3]}</small><h2>{data[0]}</h2><p>{data[2]}</p><div className="twobtn"><button><ImageIcon/> RENDER GALLERY</button><button><Film/> WATCH FULL EXPERIENCE</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);