import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Play,ArrowRight,ShieldCheck,Gamepad2,Box,Glasses,Plane,Cpu,ChevronRight,X,Image as ImageIcon,Film}from'lucide-react';import'./styles.css';
const I=n=>`/images/new-${String(n).padStart(2,'0')}.webp`;
const spaces=[
['Robotics & Drone',I(15),'Hands-on robotics and drone learning environment supporting autonomous systems, prototyping, sensing and applied research.','Robotics · Drones · Engineering'],
['VR & Immersive Lab',I(17),'Immersive virtual and extended reality environments for simulation, visualization, design review and interdisciplinary research.','VR · XR · Simulation'],
['Drone Cage',I(16),'Protected flight and robotics testing environment supporting supervised drone instruction, autonomy and research.','Drones · Testing · Research'],
['Presentation Room',I(23),'Technology-rich presentation environment with large-format visualization for lectures, demonstrations, reviews and events.','Presentation · Visualization · Events'],
['Flexible Learning',I(24),'Adaptable teaching and collaboration space for workshops, team projects, instruction and interdisciplinary learning.','Teaching · Workshops · Collaboration']];
const tech=[
['VR / XR Headsets','/images/tech-vr.png','Immersive headsets and supporting accessories for virtual reality, spatial computing and simulation.','Students, faculty, researchers','Virtual labs, design review, simulation, immersive instruction'],
['AI Workstations','/images/tech-ai.png','High-performance computing stations configured for AI development, visualization, data science and creative technology.','Students, researchers, project teams','Model development, visualization, coding, data research'],
['Robotics Platforms','/images/tech-robotics.png','Programmable robotic systems for autonomy, controls, sensing and applied engineering.','Engineering, CS, research teams','Prototyping, autonomy, controls and interdisciplinary projects'],
['Drone Systems','/images/tech-drone.png','Drone platforms supported by a protected cage environment for safe flight testing and instruction.','Robotics teams, faculty, researchers','Flight training, autonomy, sensing, mapping and research']];
function Btn({children,onClick,ghost=false}){return <button className={ghost?'btn ghost':'btn'} onClick={onClick}>{children}<ArrowRight size={16}/></button>}
function App(){const[page,setPage]=useState('Home'),[modal,setModal]=useState(null);const go=p=>{setPage(p);scrollTo({top:0,behavior:'smooth'})};const tabs=['Vision','Spaces','Technology','Esports','Safety','Videos','Contact'];return <div><header><button className="wordmark" aria-label="Home" onClick={()=>go('Home')}><img src="/images/hampton-logo.png" alt="Hampton University"/></button><nav>{tabs.map(t=><button key={t} className={page===t?'active':''} onClick={()=>go(t)}>{t}</button>)}</nav><Btn onClick={()=>go('Invest')}>INVEST NOW</Btn></header><main>{page==='Home'?<Home go={go}/>:page==='Spaces'?<Explore setModal={setModal}/>:page==='Technology'?<Technology/>:page==='Esports'?<Esports go={go}/>:page==='Safety'?<Safety/>:page==='Videos'?<Videos/>:page==='Vision'?<Vision/>:page==='Invest'?<Simple title="INVEST IN THE FUTURE" head="HELP BUILD WHAT'S NEXT." img={I(8)} text="A donor-focused destination for the vision, opportunities for support and Hampton University's approved giving pathway."/>:<Simple title="CONTACT" head="CONNECT WITH THE CENTER." img={I(2)} text="Contact information, design-team details and Hampton-approved project contacts can be added here as the campaign advances."/>}</main><footer><b>HAMPTON UNIVERSITY · TECHNOLOGY & AI CENTER</b><span>THE STANDARD OF EXCELLENCE</span></footer>{modal&&<Modal data={modal} close={()=>setModal(null)}/>}</div>}
function Landing({enter}){return <section className="landing"><div className="landingMedia"><img src="/images/portal-boat-ai-center.webp"/></div><div className="landingShade"></div><div className="portalHud"><span>HAMPTON UNIVERSITY</span><b>TECHNOLOGY & AI CENTER</b></div><div className="landingCopy"><span className="kicker">ARRIVING AT HAMPTON UNIVERSITY</span><h1>ENTER THE<br/><i>FUTURE.</i></h1><p>A cinematic waterfront arrival into Hampton's Technology & AI Center.</p><button className="enter" onClick={enter}><Play fill="currentColor"/> ENTER THE EXPERIENCE</button></div><div className="loadPanel"><b>SYSTEM ARRIVAL</b><span className="done">✓ CAMPUS IDENTIFIED</span><span>◉ LOADING SPACES</span><span>◉ LOADING VIDEOS</span><span>◉ PREPARING EXPERIENCE</span><button onClick={enter}>READY TO DONATE? <ArrowRight size={15}/></button></div></section>}
function Home({go}){return <><section className="hero"><div className="heroCopy"><span className="kicker">HAMPTON UNIVERSITY · TECHNOLOGY & AI CENTER</span><h1>THE FUTURE<br/>LIVES <i>HERE.</i></h1><p>A collaborative research and learning environment built around immersive technology, health simulation, robotics, AI, esports and the ideas that come next.</p><div className="row"><Btn onClick={()=>go('Spaces')}>EXPLORE THE CENTER</Btn><Btn ghost onClick={()=>go('Videos')}><Play size={15}/> WATCH THE VISION</Btn></div></div><div className="trueHolo"><img src={I(4)}/><span>ARCHITECTURAL HOLOGRAM // CENTER MODEL</span></div></section><section className="quick"><button onClick={()=>go('Spaces')}>06+ <span>Signature Spaces</span></button><button onClick={()=>go('Technology')}>TECH <span>Equipment + Systems</span></button><button onClick={()=>go('Esports')}>HU <span>Esports Experience</span></button><button onClick={()=>go('Safety')}>SAFE <span>Standards + Operations</span></button></section><section className="split"><img src={I(8)}/><div><span className="kicker">PEOPLE · PURPOSE · POSSIBILITIES</span><h2>A CENTER BUILT TO<br/>CONNECT DISCIPLINES.</h2><p>Explore spaces as individual stories, understand the technology going inside them, and see how each environment can support student learning, faculty research and industry collaboration.</p><Btn onClick={()=>go('Spaces')}>ENTER SPACES</Btn></div></section></>}
function Vision(){return <><section className="pageHero"><span className="kicker">DESIGN VISION</span><h1>THE STANDARD OF EXCELLENCE,<br/>REIMAGINED.</h1><p>The Technology & AI Center is envisioned as a flexible research and learning facility inside the Hampton Student Center—supporting science, engineering, healthcare, creative technology, career development and industry partnership.</p></section><section className="wideImage"><img src={I(6)}/></section></>}
function Explore({setModal}){return <><section className="pageHero"><span className="kicker">SPACES</span><h1>EXPLORE THE CENTER.</h1><p>Explore each environment through its render, purpose, student uses and future full-experience video.</p></section><section className="spaceGrid">{spaces.map(s=><article className="space" key={s[0]}><img src={s[1]}/><div><small>{s[3]}</small><h2>{s[0]}</h2><p>{s[2]}</p><div className="twobtn"><button onClick={()=>setModal(s)}><ImageIcon/> VIEW GALLERY</button><button onClick={()=>setModal(s)}><Film/> FULL VIDEO</button></div></div></article>)}</section></>}
function Technology(){return <><section className="pageHero"><span className="kicker">TECHNOLOGY CATALOG</span><h1>WHAT'S GOING<br/>INSIDE.</h1><p>Browse the Center's technology like a premium equipment catalog—what it is, who can use it, and what it unlocks. No pricing is shown.</p></section><section className="catalog">{tech.map(([n,img,d,who,use],i)=><article key={n}><div className="productVisual"><img src={img} alt={n}/><span>TECH {String(i+1).padStart(2,'0')}</span></div><div className="productCopy"><small>HAMPTON TECHNOLOGY SYSTEM</small><h2>{n}</h2><p>{d}</p><dl><dt>WHO COULD USE IT</dt><dd>{who}</dd><dt>STUDENT + RESEARCH VALUE</dt><dd>{use}</dd><dt>INCLUDES</dt><dd>Core system · supporting accessories · instructional integration · shared-use setup</dd></dl><button>VIEW EQUIPMENT DETAILS <ChevronRight/></button></div></article>)}</section></>}
function Esports({go}){return <><section className="pageHero"><span className="kicker">HAMPTON ESPORTS</span><h1>PLAY. COMPETE.<br/>CREATE.</h1><p>Hampton's esports initiative expands competitive gaming within the HBCU community while connecting students to technology, leadership and community building.</p></section><section className="esportsCopy"><article><h2>STUDENT-LED COMPETITION + COMMUNITY</h2><p>Hampton Esports supports competitive play for students interested in gaming as both a sport and a potential career pathway. The program creates opportunities to build teams, host organized experiences and connect gaming with technology and student leadership.</p></article><article><h2>EXPANDING REPRESENTATION</h2><p>Hampton is part of the broader growth of esports across HBCUs, helping expand representation in competitive gaming and create new opportunities for students of color across the industry.</p></article><article><h2>BEYOND THE GAME</h2><p>The esports experience can connect competition with broadcasting, production, computing, creative technology, teamwork, events and career development.</p><Btn onClick={()=>go('Videos')}>WATCH ESPORTS EXPERIENCE</Btn></article></section></>}
function Safety(){return <><section className="pageHero"><span className="kicker">SAFETY + STANDARDS</span><h1>INNOVATION,<br/>RESPONSIBLY.</h1><p>Technology-rich environments require clear training, supervision and operating standards. Safety information is presented as guidance and remains subject to Hampton University policies, manufacturer requirements and applicable standards.</p></section><section className="standards safetyText"><article><b>01</b><h3>Operational Safety</h3><p>Training, supervision, equipment check-out, room-specific procedures and controlled access for specialized systems.</p></article><article><b>02</b><h3>VR / XR Use</h3><p>Managed sessions, clear play areas, equipment sanitation, accessibility considerations and manufacturer-recommended use practices.</p></article><article><b>03</b><h3>Robotics + Drones</h3><p>Protected testing areas, pre-flight checks, supervised operation, defined shutdown procedures and separation from public circulation.</p></article><article><b>04</b><h3>AI + Data</h3><p>Secure systems, responsible data handling, approved access and research practices aligned with university requirements.</p></article><article><b>05</b><h3>Accessibility</h3><p>Inclusive routes, interfaces and learning environments designed to support broad student access and participation.</p></article><article><b>06</b><h3>Emergency Procedures</h3><p>Posted room procedures, equipment isolation, incident reporting and coordination with university emergency protocols.</p></article></section></>}
function Videos(){let vids=[[I(5),'Center Vision'],[I(15),'Health + Anatomy'],[I(19),'Immersive Athletics'],[I(17),'Robotics + Drones'],[I(20),'Esports'],[I(18),'Center Arrival']];return <><section className="pageHero"><span className="kicker">VIDEO EXPERIENCES</span><h1>SEE THE CENTER<br/>IN MOTION.</h1><p>Each card is ready to connect to a Cloudinary-hosted full video while keeping large video files out of the website repository.</p></section><section className="videoGrid">{vids.map(v=><article><img src={v[0]}/><div className="play"><Play fill="currentColor"/></div><h3>{v[1]}</h3><span>FULL EXPERIENCE VIDEO SLOT</span></article>)}</section></>}
function Simple({title,head,img,text}){return <><section className="pageHero"><span className="kicker">{title}</span><h1>{head}</h1><p>{text}</p></section><section className="wideImage"><img src={img}/></section></>}
function Modal({data,close}){return <div className="modal" onClick={close}><div onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><img src={data[1]}/><small>{data[3]}</small><h2>{data[0]}</h2><p>{data[2]}</p><div className="twobtn"><button><ImageIcon/> RENDER GALLERY</button><button><Film/> WATCH FULL EXPERIENCE</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);